language: c

compiler:
  - gcc

matrix:
  include:
    # Ubuntu Trusty, Xenial and Bionic
    - dist: trusty

    - dist: bionic

    # MacOs
    - os: osx

    # Windows
    # - os: windows

install: 
  - mkdir build
  - cd build
  

jobs:
  include:
      - dist: trusty
      - before_script : cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ../
      - dist: bionic
      - before_script : cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ../
      - os: osx
      - before_script : cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ../
      - if: (dist IN (trusty,bionic) OR os = osx)
      - os: windows
      - before_script : cmake -DCMAKE_INSTALL_PREFIX=%HOMEPATH%\local ..\
      - if: os = windows

script:
  - make
