language: c

compiler:
  - gcc

matrix:
  include:
    # Ubuntu Trusty, Xenial and Bionic
    - dist: trusty

    - dist: bionic

    # MacOs
    - os: osx

    # Windows
#    - os: windows
#      env:
#         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

install: 
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ../

script:
  - make
