language: c

compiler:
  - gcc

matrix:
  include:
    # Ubuntu Trusty, Xenial and Bionic
    - dist: trusty

    - dist: bionic

    # MacOs
    - os: osx

    # Windows
    - os: windows

install: 
  - mkdir build
  - cd build
  
before_script : cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ../

jobs:
  include:
      - if: os = windows
      - before_script : cmake -DCMAKE_INSTALL_PREFIX=%HOMEPATH%\local ..\

script:
  - make
